name: reminder_app
description: "Flutter hat覺rlat覺c覺 uygulamas覺"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path_provider:
  flutter_analog_clock: ^1.0.3
  one_clock: ^2.0.1
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
